permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap

name: Jordan Harrod
url: http://harrodjordan.github.io
description: Newly outspoken about science communication. Longtime doer of random projects. 
twitter: jordanbharrod
baseurl: /

google_analytics: UA-120508959-1
